### ISSUE TITLE
document requirement for Compliance Operator

### ISSUE THREAD

**Issue by magreenberg** [open-cluster-management-io/policy-collection#116]
A number of the policies in the "stable" collection depend on CRDs created by the Compliance Operator:
* ScanSettingBinding
* ComplianceSuite
* ComplianceCheckResult
A number of policies depend on a hardcoded namespace named: openshift-compliance

The CRDs above are created by the Compliance Operator, yet there is no mention in the documentation that the operator needs to be installed. Please update the documentation to include the requirement.

**Comment by ch-stark** [comment]
@magreenberg  thanks for opening the issue. I had a first review and both in stable and community we document that installing Compliance Operator is a requirement.  However I'll review with our Doc-Team and update the issue.
