### ISSUE TITLE
Add 'enforcementAction: dryrun' to Gatekeeper policies

### ISSUE THREAD

**Issue by michaelkotelnikov** [open-cluster-management-io/policy-collection#127]
Most policies in the collection are using `remediationAction: inform`, so policies are not 'enforced' out of the box.

Regarding Gatekeeper, it makes sense to `enforce` the creation of the `ConstraintTemplate` and `Constraint` objects when deploying a policy that relies on Gatekeeper. But, it would be more 'safe' to add `enforcementAction: dryrun` to the Gatekeeper's `Constraint` object definition. So the constraint is deployed, but it does not deny the creation of objects that violate the OPA policy.

For example, the next [policy](https://github.com/open-cluster-management/policy-collection/blob/main/community/CM-Configuration-Management/policy-gatekeeper-container-image-latest.yaml) denies the creation of pods with `<image-name>:latest`  image references as soon as its deployed. While this [policy](https://github.com/openshift-4-compliance/openshift-4-compliance-automation/blob/master/redhat-acm/trusted-image-sources/gatekeeper-disallow-image-tags/gatekeeper-disallow-image-tags.yaml) (from a 3rd party repository) is doing the same thing without enforcing the admission controller (since it has `enforcementAction: dryrun` defined in the `Constraint` object). This way, the policy monitors violations that Gatekeeper triggers, but it does not disallow the creation of objects.

Policy users can choose to remove `enforcementAction: dryrun` from the policy definition if they'd like the policy to be enforced in their environment.

**Comment by ch-stark** [comment]
thanks Michael, this sounds like a great idea

**Comment by ch-stark** [comment]
@michaelkotelnikov we are working on examples which will be contributed to the community-section.
For those examples we don't need any change, we still need enforce and put dry-run into the Gatekeeper-Contraint.

Let me know if you agree

**Comment by gparvin** [comment]
I proposed a PR to apply this: https://github.com/open-cluster-management/policy-collection/pull/198
I agree that we should use the dryrun by default.

**Comment by michaelkotelnikov** [comment]
Awesome @gparvin lgtm

**Comment by gparvin** [comment]
Closing this a fixed.
