### ISSUE TITLE
Deploy policies using GitOps in an air-gap environment

### ISSUE THREAD

**Issue by YonatanGolick** [open-cluster-management-io/policy-collection#162]
Hi guys,
So I forked this repo to an disconnected environment and followed the procedure step by step but could not implement the policies using gitops. 
The only information I have is the logs from the klusterlet-addon-appmgr pod:
`Exit reconciling subscription. `
The policies are in a private gitLab instance.

**Comment by ch-stark** [comment]
Hi Yonatan, I assume you are missing proxy settings. In 2.3.3 we have fixed an issue in this are

**Comment by gparvin** [comment]
@YonatanGolick Was the information provided by @ch-stark helpful?  If not, we need to see if there are more details that can be provided on what policies are being used and what problems have happened.  Thanks!

**Comment by gparvin** [comment]
Please re-open this if necessary.  Thanks!
