### ISSUE TITLE
Provide more examples and maybe a own folder for templatized policies

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management-io/policy-collection#204]
in 2.3,2.4 we introducted Templating.  https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/governance/governance#support-templates-in-config-policies
This issue is about providing more examples

**Comment by ch-stark** [comment]
The following examples should be provided:

fromSecret function
fromConfigmap function
fromClusterClaim function
lookup function
base64enc function
base64dec function
indent function
autoindent function
toInt function
toBool function

+ Hub-Side templating

**Comment by ch-stark** [comment]
https://docs.google.com/document/d/1E32BGirmArcdVXgxAWSatQ43T9LhtdLSbiKt3PmjaSA/edit#heading=h.tieo10odkehd

**Comment by ch-stark** [comment]
* we have ACS and Logforwarding

**Comment by gparvin** [comment]
@ckandag has added several templating samples.  I'm not sure if all of the templating functions are covered, but there are some cool use cases such as https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-enable-if-ns-exists-templatized.yaml

**Comment by ch-stark** [comment]
@gparvin @ckandag we got another example to Handle MachineSets:  https://gist.github.com/ch-stark/95c37deb854405b7203a3fedacdec4d2

**Comment by gparvin** [comment]
@ch-stark Now that people can create the MachineSets, I expect they will want to make sure the MachineSet is Compliant and "ready" before applying the next policy which would use the MachineSets.
