### ISSUE TITLE
Provide Policies for RHACM-Observability

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management-io/policy-collection#225]
https://cloud.redhat.com/blog/viewing-cluster-alerts-warnings-or-recommendations-in-an-aggregated-view-with-red-hat-advanced-cluster-management-observability

**Comment by gparvin** [comment]
Is this policies related to observability configuration, insights or maybe some kind of alert manager integration?

**Comment by gparvin** [comment]
OPP policy set has the ability to enable Observability.  It's really still a work in progress but could be a nice sample for this: https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus

**Comment by gparvin** [comment]
The OPP PolicySet is stable now.  We'll be expanding to new platforms as we are able.  Re-open if you need something else here.
