### ISSUE TITLE
RBAC policy to restrict Rights at Namespace Levels for Managed Cluster

### ISSUE THREAD

**Issue by sahilsethi12** [open-cluster-management-io/policy-collection#251]
we have below requirement which we wanted to check :

Lets say user has 3 namespaces in managed cluster A, B ,C , he wants a USERA to access and view only project a from ACM console or Grafana console 

similarly he wants his other user lets say USERB to access and view only project b from ACM console or Grafana console 

He should see the resources of project A with USERA in ACM console as well as in grafana console 

As of now we can restrict user in cluster level by using the below comnands : 

oc create clusterrolebinding userA --clusterrole=open-cluster-management:view:devcluster --user=userA
oc create rolebinding userA -n devcluster --clusterrole=devclusterview --user=userA

by this commands , userA can see all namespaces in devcluster , but we want to restrict userA to see only project A.

is that possible ?
Can someone please guide us

**Comment by ch-stark** [comment]
@sahilsethi12 this can be achieved by creating RoleBindings.  A default user has no view permissions to a project

**Comment by sahilsethi12** [comment]
@ch-stark Is there any example which can be taken as reference

**Comment by ckandag** [comment]
to setup userA/B/C accesscontrol on the managed-cluster itself, you can just do something like in this policy https://github.com/stolostron/policy-collection/blob/main/community/AC-Access-Control/policy-configure-appworkloads-rbac-sample.yaml

but on the ACM hub itself you can setup user access control at managed-cluster level but not subset of namespaces on the managed-cluster.

**Comment by gparvin** [comment]
@sahilsethi12 Please provide feedback if the answers above need more details.  I'm closing this issue now hoping your question is answered.  Thanks!
