### ISSUE TITLE
Change namespace for rhacs operator installation

### ISSUE THREAD

**Issue by harpasin** [open-cluster-management-io/policy-collection#260]
The latest RHACS operator recommends the `rhacs-operator` namespace to install the operator.

[RHACS Central policy](https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-acs-operator-central.yaml) and [RHACS Secured Cluster Policy](https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-acs-operator-secured-clusters.yaml) should install operator in the `rhacs-operator`

These policies require two more templates.
1. Create `rhacs-operator` namespace.
2. Create `rhacs-operator` OperatorGroup.

If this issue is approved, I can create a PR for these policies.

**Comment by gparvin** [comment]
This issue should be fixed now.
