### ISSUE TITLE
Description, stable, non working link

### ISSUE THREAD

**Issue by marmendo** [open-cluster-management-io/policy-collection#267]
go to the examples table here
https://github.com/stolostron/policy-collection/tree/main/stable

go to the Kyverno Generate Network Policies row:
See the [Policy to install Kyverno](https://github.com/stolostron/policy-collection/blob/main/stable/CM-Configuration-Management/policy-install-kyverno.yaml).

The link returns 404

**Comment by dhaiducek** [comment]
Thank you for raising this issue! The policies were moved to `stable`, but the Kyverno installation remains in `community`, here: https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-install-kyverno.yaml
We'll investigate.

**Comment by dhaiducek** [comment]
@marmendo I've updated the links--please verify and confirm whether this issue can be closed.

**Comment by marmendo** [comment]
Confirmed. It works now. Thanks !!

**Comment by marmendo** [comment]
Solved
It works. Thanks !!
