### ISSUE TITLE
Missing multiclusterhub-operator-pull-secret from the open-cluster-management-observability namespace

### ISSUE THREAD

**Issue by jwilms1971** [open-cluster-management-io/policy-collection#297]
After running the input-acm-observabilty policies, multiclusterhub-operator-pull-secret is missing. According to the ACM installation guide this is required by the obervability service.

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/observability/observing-environments-intro#prerequisites-observability

**Comment by gparvin** [comment]
I added a change to do this.  Please let me know if this doesn't fix the problem for you.  Thanks!
