### ISSUE TITLE
Remove kubeadmin policy in policyset openshift-hardening is missing API version

### ISSUE THREAD

**Issue by jwilms1971** [open-cluster-management-io/policy-collection#350]
When deploying the policyset openshift-hardening the remove kubeadmin policy is incorrectly reporting the status when enabled in inform mode. This is because it is missing the apiVersion field.

Issue first detected on ACM2.6.1/OCP4.11.2

**Comment by ch-stark** [comment]
thanks @jwilms1971 we will fix this
