### ISSUE TITLE
ACS policies SecuredCluster

### ISSUE THREAD

**Issue by aakanmaz** [open-cluster-management-io/policy-collection#407]
Hi 
it may be good to change collection method as  EBPF. KernelModule is deprecated 

https://docs.openshift.com/acs/3.74/release_notes/374-release-notes.html#kernel-collection-module

Added 20 March 2023

Currently, secured clusters can specify three options of collection methods for runtime events: eBPF (selected by default), kernel module, or no collection. Kernel module as a collection method is deprecated in the RHACS version 3.74 release and is planned for removal in the RHACS version 4.1 release.

**Comment by dhaiducek** [comment]
@aakanmaz As the policy has been updated, would you please confirm whether this issue can be closed?

**Comment by aakanmaz** [comment]
Hi 

It may be also good to check below files. Not sure but these seems still using KernelModule if I am not missing anything

‎policygenerator/policy-sets/community/openshift-plus/input-sensor/policy-acs-sync-resources.yaml
‎community/CM-Configuration-Management/policy-acs-operator-secured-clusters.yaml
‎policygenerator/policy-sets/stable/openshift-plus/output.yaml
‎policygenerator/policy-sets/community/openshift-plus/input-sensor/policy-advanced-managed-cluster-security.yaml

**Comment by gparvin** [comment]
I addressed the additional concerns in pr #423 so closing now.
