### ISSUE TITLE
Point to Quay.io instead of OCR

### ISSUE THREAD

**Issue by jwilms1971** [open-cluster-management-io/policy-collection#424]
On vSphere platforms OCR is not automatically configured thus the script to create the bundle fails as it tries to access: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

Suggest repointing this to quay.io/openshift/origin-cli:latest

**Comment by dhaiducek** [comment]
Hi @jwilms1971! Thanks for the feedback! Unfortunately the references in the Openshift-Plus PolicySet you're referring to are currently only supported on AWS (though we'd love to start targeting vSphere in the near future for this). We'll consider this as we move toward supporting vSphere. Another consideration might be disconnected environments, so it perhaps could be handled as either an additional policy to configure this to work in various configurations or some conditional based on the platform.

If it's okay with you considering the currently supported configuration is AWS, I propose we close this issue and it can be reopened once vSphere is vetted if this is still an issue there?
