### ISSUE TITLE
Changing the storageclass from gp3-csi to gp2-csi

### ISSUE THREAD

**Issue by OdedViner** [open-cluster-management-io/policy-collection#428]
ODF-QE team test AWS with gp2-csi storageclass.

https://github.com/open-cluster-management-io/policy-collection/blob/3ab7a2838102aa93be330a65f9a4a342b6cc6e80/policygenerator/policy-sets/stable/openshift-plus/input-odf/policy-odf.yaml#L73C9-L73C26

OCS-CI code:
https://github.com/red-hat-storage/ocs-ci/blob/c4c3644a4fb97ffc91be6d865e8e71877f29c1fb/ocs_ci/deployment/aws.py#L68-L69

In addition, in order to save costs, we can use a smaller storage for acceptace suite.
For example `100Gi`

https://github.com/open-cluster-management-io/policy-collection/blob/3ab7a2838102aa93be330a65f9a4a342b6cc6e80/policygenerator/policy-sets/stable/openshift-plus/input-odf/policy-odf.yaml#L72

**Comment by dhaiducek** [comment]
As a PR was merged, I'm assuming this issue can be closed, but please reopen if this is not the case.
